plugins:
  ai_topic_summary_enabled:
    default: true
    client: true
  ai_topic_summary_open_ai_token:
    default: ''
    client: false
  ai_topic_summary_open_ai_model:
    default: 'text-davinci-003'
    client: false
  ai_topic_summary_max_response_tokens:
    default: 200
    client: false
  ai_topic_summary_character_limit:
    default: 20000
    client: false
  ai_topic_summary_enabled_min_posts:
    default: 5
    client: false
  ai_topic_summary_enabled_post_interval_rerun:
    default: 3
    client: false
  ai_topic_summary_permitted_in_private_messages:
    default: false
    client: false
  ai_topic_summary_permitted_all_categories:
    default: true
    client: false
  ai_topic_summary_permitted_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  ai_topic_summary_downvote_refresh_threshold:
    client: false
    default: 1

