plugins:
  ai_topic_summary_enabled:
    default: true
    client: true
  ai_topic_summary_open_ai_token:
    default: ''
    client: false
  ai_topic_summary_open_ai_model_custom:
    default: false
    client: false
  ai_topic_summary_open_ai_model_custom_name:
    default: ''
    client: false
  ai_topic_summary_open_ai_model_custom_type:
    default: 'chat'
    client: false
    type: enum
    choices:
      - chat
      - completions
  ai_topic_summary_open_ai_model:
    client: false
    type: enum
    default: gpt-3.5-turbo
    choices:
      - gpt-3.5-turbo
      - gpt-4
      - text-davinci-003
      - text-davinci-002
  ai_topic_summary_request_max_response_tokens:
    default: 200
    client: false
  ai_topic_summary_request_temperature:
    client: false
    default: 100
    min: 0
    max: 100
  ai_topic_summary_request_top_p:
    client: false
    default: 100
    min: 0
    max: 100
  ai_topic_summary_request_frequency_penalty:
    client: false
    default: 0
    min: -200
    max: 200
  ai_topic_summary_request_presence_penalty:
    client: false
    default: 0
    min: -200
    max: 200
  ai_topic_summary_character_limit:
    default: 15000
    client: false
  ai_topic_summary_post_limit:
    default: 40
    client: false
  ai_topic_summary_strip_quotes:
    default: true
    client: false
  ai_topic_summary_enabled_min_posts:
    default: 5
    client: false
  ai_topic_summary_enabled_post_interval_rerun:
    default: 3
    client: false
  ai_topic_summary_permitted_in_private_messages:
    default: false
    client: false
  ai_topic_summary_permitted_all_categories:
    default: true
    client: false
  ai_topic_summary_permitted_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  ai_topic_summary_downvote_refresh_threshold:
    client: false
    default: 1
  ai_topic_summary_rely_on_layouts_widget_instead:
    client: true
    default: false
  ai_topic_summary_enable_auto_tagging:
    client: false
    default: false
  ai_topic_summary_auto_tagging_username:
    client: false
    default: ""
