plugins:
  ai_topic_summary_enabled:
    default: true
    client: true
  ai_topic_summary_expose_as_excerpt:
    default: false
    client: false
  ai_topic_summary_open_ai_token:
    default: ''
    client: false
  ai_topic_summary_open_ai_model_custom:
    default: false
    client: false
  ai_topic_summary_open_ai_model_custom_name:
    default: ''
    client: false
  ai_topic_summary_open_ai_model:
    client: false
    type: enum
    default: gpt-4o-mini
    choices:
      - gpt-3.5-turbo
      - gpt-4o
      - gpt-4o-mini
      - gpt-4-turbo
      - gpt-4
  ai_topic_summary_request_max_response_tokens:
    default: 200
    client: false
  ai_topic_summary_request_temperature:
    client: false
    default: 100
    min: 0
    max: 100
  ai_topic_summary_request_top_p:
    client: false
    default: 100
    min: 0
    max: 100
  ai_topic_summary_request_frequency_penalty:
    client: false
    default: 0
    min: -200
    max: 200
  ai_topic_summary_request_presence_penalty:
    client: false
    default: 0
    min: -200
    max: 200
  ai_topic_summary_character_limit:
    default: 15000
    client: false
  ai_topic_summary_post_limit:
    default: 40
    client: false
  ai_topic_summary_strip_quotes:
    default: true
    client: false
  ai_topic_summary_enabled_min_posts:
    default: 5
    client: false
  ai_topic_summary_enabled_post_interval_rerun:
    default: 3
    client: false
  ai_topic_summary_permitted_in_private_messages:
    default: false
    client: false
  ai_topic_summary_permitted_all_categories:
    default: true
    client: false
  ai_topic_summary_permitted_categories:
    client: false
    default: ''
    type: category_list
    list_type: "compact"
  ai_topic_summary_downvote_refresh_threshold:
    client: false
    default: 1
  ai_topic_summary_rely_on_sidebar_widget_instead:
    client: true
    default: false
  ai_topic_summary_enable_topic_thumbnail:
    client: false
    default: false
  ai_topic_summary_remove_prior_thumbnail:
    client: false
    default: true
  ai_topic_summary_enable_auto_tagging:
    client: false
    default: false
  ai_topic_summary_auto_tagging_strategy:
    client: false
    default: "completion"
    type: enum
    choices:
      - completion
      - embeddings
  ai_topic_summary_auto_tagging_username:
    client: false
    default: ""
  ai_topic_summary_auto_tagging_embeddings_enabled:
    client: false
    default: false
  ai_topic_summary_auto_tagging_embeddings_model:
    client: false
    type: enum
    default: text-embedding-ada-002
    choices:
      - text-embedding-ada-002
      - text-embedding-3-small
  ai_topic_summary_auto_tagging_embeddings_similarity_threshold:
    client: false
    default: 0.8
    min: 0
    max: 1
  ai_topic_summary_auto_tagging_open_ai_embeddings_char_limit:
    client: false
    default: 11500
  ai_topic_summary_verbose_console_logging:
    client: false
    default: false
  ai_topic_summary_verbose_rails_logging:
    client: false
    default: false
  ai_topic_summary_verbose_rails_logging_destination_level:
    client: false
    default: "info"
    type: enum
    choices:
      - info
      - warn
